### ISSUE TITLE
data-deleteDelay

### ISSUE THREAD

**Issue by mortenhjort** [straversi/Typer.js#6]
If I understand correct then this setting would allow a word to be fully typed for x-amount of time before its deleted and a new work is made aint that correct? I´ve tried to insert a value here: www.getskillup.com. But no matter how high a value nothing changes.

**Comment by straversi** [comment]
Yes, here's a snippet from the home page as an example:

`<h1>Typer.js is <span class="typer" id="main" data-words="great,fun,lightweight,easy" data-colors="white" data-delay="100" data-deleteDelay="1000"></span><span class="cursor" data-owner="main"></span></h1>`

Changing `data-deleteDelay="1000"` to `data-deleteDelay="5000"` changes the delay between word completion and deletion from 1 to 5 seconds.

Feel free to attach a snippet if it's still not working and we can figure it out.

**Comment by mortenhjort** [comment]
Thanks for the reply! I´ve added it here: http://getskillup.com, but it seems it still dont work. This is whats inserted: data-deleteDelay="50000"

**Comment by straversi** [comment]
Thanks for the link-- It looks like you're running into an issue that we fixed in f282a43f10de150d002a55c0aaa623d0a0367c12, where the deleteDelay variable was not being retrieved properly. Getting the newest version of Typer.js solved the problem when I tried it on your page!

**Comment by straversi** [comment]
Closing this due to age. Feel free to re-open if necessary
