### ISSUE TITLE
OS License Type

### ISSUE THREAD

**Issue by gaganc** [straversi/Typer.js#7]
Hi,

Would it be possible to clarify under what license is this code released? My best guess would be MIT but i couldn't find any reference anywhere (i apologize if i missed anything but i also looked at the website but couldn't find). It would be extremely helpful if you can clarify or add the license file in the root folder

Thanks Much,
Gagan

**Comment by straversi** [comment]
Good idea, thanks for bringing this up. f3fd191

**Comment by gaganc-soltech** [comment]
Awesome, thanks for the quick response !
